### ISSUE TITLE
Add possibility to add/remove stopovers

### ISSUE THREAD

**Issue by fabianbormann** [nav-e/nav-e#21]
See our [polymer reference](https://github.com/Greennav/GreenNav/tree/polymer_reference) for instance 

<img src="https://cloud.githubusercontent.com/assets/1525818/20544808/0f49517e-b10c-11e6-916b-ac4a3354be6a.gif">

**Comment by arshdkhn1** [comment]
@fabianbormann I would like to work on this. I have added dynamic addition of stopovers...
