### ISSUE TITLE
Munich to Augsburg route does not display

### ISSUE THREAD

**Issue by anurag1018** [nav-e/nav-e#31]
![greennav](https://cloud.githubusercontent.com/assets/17769227/24030674/303975a6-0b04-11e7-933b-0316449092e8.gif)

I have cloned both GreenNav and rt-library but the demo does not seem to work

**Comment by maxlorenz** [comment]
Hi @anurag1018 !

you have to select a starting point/destination from the suggestions that pop up. the demo route was replaced with all of monaco (so you have "real" routing with minimal memory usage). I will edit the README to clarify that further :smile:

**Comment by ar5had** [comment]
@maxlorenz https://github.com/Greennav/GreenNav/issues/35
