### ISSUE TITLE
Routing is broken

### ISSUE THREAD

**Issue by maxlorenz** [nav-e/nav-e#32]
When the rt-library is started, you get suggestions but the `GET ROUTE`-button isn't working. Error message from the JS console:

`TypeError: _this.state.route is undefined`

**Comment by arshdkhn1** [comment]
Hi, It look like the route state variable was accidentally removed by me when I was trying to remove react warnings.. I have added it back and I want to apologies for the problems faced by anyone.

**Comment by ar5had** [comment]
Hi, I removed the route variable and embedded into new autocompletes state variable. But I forgot to change one place where old route variable was used. I apologies for the inconvenience caused.
