### ISSUE TITLE
Route request url handler doesn't exist in rt library.

### ISSUE THREAD

**Issue by ar5had** [nav-e/nav-e#35]
When i hit `GET ROUTE` button, a request is sent to `/from/:id/to/:id` but there is no handler for these request in rt-library. rt-library handles only `/astar/from/:id/to/:id` and `/dijkstra/from/:id/to/:id`.. 

`getRoute` method:
``` js
getRoute = (waypoints) => {
    const startOsmId = waypoints[0];
    const destinationOsmId = waypoints[waypoints.length - 1];
    // this url req is not handled by rt-library
    const url = `${GreenNavServerAddress}from/${startOsmId}/to/${destinationOsmId}`;
    ...
```

**Comment by maxlorenz** [comment]
Hm it should have been changed by commit 09dbb0as

**Comment by ar5had** [comment]
Hmm, I was a bit hesitant to make that change myself so I opened this issue.
