### ISSUE TITLE
A blank space or group of black spaces in Text-fields(From & To) generate 404 error 

### ISSUE THREAD

**Issue by lemetice** [nav-e/nav-e#36]
When a blank space or group of blank spaces is used in the text-fields (From and To) the error `http://localhost:6833/search/ 404 (Not Found)` is generate.

**Comment by lemetice** [comment]
This error is actually generated because the blank space is not an address. That is the backend expects a url with parameter like `http://localhost:6833/search/`**monaco**
A way to solve this will be to interactively, block (don't allow) the first character in a text-field to be a space, or group of spaces. Since no address starts with blank space(s)

**Comment by ar5had** [comment]
@lemetice As of now only one route(that is mentioned in readme) is working.

**Comment by maxlorenz** [comment]
Actually more routes do work but many don't - but that's on the segmented OSM data we use :wink:

**Comment by ar5had** [comment]
Ohh

**Comment by shreyakupadhyay** [comment]
This issue can be resolved by encoding string as a Uniform Resource Identifier component. When a user inputs the address, the string will get encoded and the corresponding search request will be sent.
