### ISSUE TITLE
Displaying results after route is calculated

### ISSUE THREAD

**Issue by hnrqer** [nav-e/nav-e#49]
After the route is calculated, we could show to the user the Distance, Duration, and Battery Consumption of the trip.

Firstly we can work with a mock version with hardcoded values, so later we can really calculate this information.

**Comment by hnrqer** [comment]
![routeresultsdisplay](https://cloud.githubusercontent.com/assets/1770506/24486303/ca656c70-1509-11e7-9322-bc5bbdeeb64b.png)

**Comment by fabianbormann** [comment]
Generally a good idea, but in my opinion a hardcoded gui mock does not make sense.. For now we don't know if we ever get this data from our backend (currently not in the planning).. so this gui feature is not needed for now. sry for the delay in my response.

**Comment by hnrqer** [comment]
I was thinking that the rt-library could return to the front-end the total distance of the route through the haversine formula (which is already implemented in the osm-lib.js rt library).

The travel duration could then be roughly estimated  by the use of the speed limit of the coordinates found. In OMS we have http://wiki.openstreetmap.org/wiki/Key:maxspeed and http://wiki.openstreetmap.org/wiki/Speed_limits.

Regarding the battery consumption there is still no purpose for implementation for now.
