### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by maxlorenz** [nav-e/nav-e#56]
Some dependencies are outdated and should be updated

**Comment by abhishek71994** [comment]
Can I use https://www.npmjs.com/package/npm-check-updates this package is installed globally and it won't be added to the project

**Comment by abhishek71994** [comment]
I ran an ``` npm outdated ``` and saw the potential outdated packages. Will make a PR after updating them.

**Comment by abhishek71994** [comment]
Update the PR, check it out.
