### ISSUE TITLE
Remove stutter with Google Maps view

### ISSUE THREAD

**Issue by fabianbormann** [nav-e/nav-e#7]
After clicking around for some time, the Google Maps sometimes starts to stutter when it's dragged

**Comment by fabianbormann** [comment]
Hey @maxlorenz for me the error disappeared by changing the map type from leaflet back to osm-map aa02565 (I had to enable restamp in dom-if) -> Could you confirm that?  

P.S.: Waypoint drawing now works as expected in Google and OSM :tada:

**Comment by maxlorenz** [comment]
Yes, confirmed! 👍
